<a href="https://colab.research.google.com/github/Dhivya-kuppusamy/Machine-learning/blob/main/neural_network_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

In [ ]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array([[1],[0],[1]])

In [ ]:
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def derivative_sigmoid(x):
  return x*(1-x)

In [ ]:
#pass input,epoch,learning rate,output
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,hidden_neurons))
bo=np.random.uniform(size=(1,hidden_neurons))

In [ ]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr


In [ ]:
output

array([[0.96366825, 0.96265252, 0.96337156],
       [0.05015713, 0.05083563, 0.05008501],
       [0.97460269, 0.97446796, 0.9749077 ]])

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# Convert target variable to one-hot encoding
y_one_hot = np.zeros((y.shape[0], np.unique(y).shape[0]))
y_one_hot[np.arange(y.shape[0]), y.flatten()] = 1

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Normalize the features
X_train /= np.max(X_train, axis=0)
X_test /= np.max(X_test, axis=0)

# Initialize variables
epoch = 5000
lr = 0.1
input_neurons = X_train.shape[1]
hidden_neurons = 5
output_neurons = y_train.shape[1]

# Initialize weights and bias
wh = np.random.uniform(size=(input_neurons, hidden_neurons))
bh = np.random.uniform(size=(1, hidden_neurons))
wo = np.random.uniform(size=(hidden_neurons, output_neurons))
bo = np.random.uniform(size=(1, output_neurons))

# Training the model
for i in range(epoch):
    # Forward
    hidden_input = np.dot(X_train, wh) + bh
    hidden_activation = 1 / (1 + np.exp(-hidden_input))
    output_layer = np.dot(hidden_activation, wo) + bo
    output = 1 / (1 + np.exp(-output_layer))

    # Backward
    E = y_train - output
    slope_output = output * (1 - output)
    slope_hidden = hidden_activation * (1 - hidden_activation)

    d_output = E * slope_output
    error_hidden = d_output.dot(wo.T)
    d_hidden = error_hidden * slope_hidden

    # Update weights and bias
    wo += hidden_activation.T.dot(d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X_train.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

# Forward pass on test data
hidden_input_test = np.dot(X_test, wh) + bh
hidden_activation_test = 1 / (1 + np.exp(-hidden_input_test))
output_layer_test = np.dot(hidden_activation_test, wo) + bo
output_test = 1 / (1 + np.exp(-output_layer_test))

# Convert predicted probabilities to class labels
predicted_labels = np.argmax(output_test, axis=1)
true_labels = np.argmax(y_test, axis=1)

# Calculate accuracy
accuracy = np.mean(predicted_labels == true_labels)
print("Accuracy:", accuracy)

Accuracy: 0.9666666666666667
